java8:
 image: flinkdevelopmentsuite_java8

flink:
 image: flinkdevelopmentsuite_flink

flinkdev:
 image: flinkdevelopmentsuite_flinkdev

training:
 image: flinkdevelopmentsuite_training

emacs:
  image: flinkdevelopmentsuite_emacs
  extends:
    file: ./emacs/docker-compose.yml
    service: emacs
