---
  emacs:
    build: .
    volumes: 
      - ./.sbt:/home/$EMACS_USER/.sbt
      - ./.ivy2:/home/$EMACS_USER/.ivy2
      - ./.emacs.d:/home/$EMACS_USER/.emacs.d
    environment:
      - DISPLAY=192.168.99.1:0
