---
  emacs:
    build: .
    volumes: 
      - ./.sbt:/home/$DEV_USER/.sbt
      - ./.ivy2:/home/$DEV_USER/.ivy2
      - ./.emacs.d:/home/$DEV_USER/.emacs.d
      - $PWD/:/opt/mounted_project
    environment:
      - DISPLAY=192.168.99.1:0
    mem_limit: 2000000000
    memswap_limit: 2000000000
    privileged: true
